/**
 * SkillSync E2E Test Suite - 325 Distinct Test Cases Metadata & Definition
 * Target URL: https://skillsync-app-rho.vercel.app
 * Account: princeirfan282@gmail.com / 123user123
 */

const BASE_URL = 'https://skillsync-app-rho.vercel.app';

const testCases = [
  // ==========================================
  // MODULE A: LANDING PAGE & PUBLIC NAVIGATION (TC-001 to TC-055)
  // ==========================================
  { id: 'TC-001', category: 'Landing Page', title: 'Verify Homepage Title & SEO Tags', target: 'head > title', expected: 'SkillSync - Skill Exchange & Career Intelligence Platform' },
  { id: 'TC-002', category: 'Landing Page', title: 'Verify Brand Logo Banner Visibility', target: 'nav img[alt*="Logo"]', expected: 'Logo image rendered' },
  { id: 'TC-003', category: 'Landing Page', title: 'Verify Brand Text "SkillSync" Link', target: 'nav a[href="/"]', expected: 'Navigates to root homepage' },
  { id: 'TC-004', category: 'Landing Page', title: 'Verify Header Navigation "Explore" Link', target: 'nav a[href="/explore"]', expected: 'Redirects to Explore page' },
  { id: 'TC-005', category: 'Landing Page', title: 'Verify Header Navigation "How it works" Link', target: 'nav a[href="/#how"]', expected: 'Smooth scrolls to #how section' },
  { id: 'TC-006', category: 'Landing Page', title: 'Verify Header Navigation "Skills" Link', target: 'nav a[href="/#skills"]', expected: 'Smooth scrolls to #skills section' },
  { id: 'TC-007', category: 'Landing Page', title: 'Verify Header Navigation "Stories" Link', target: 'nav a[href="/#stories"]', expected: 'Smooth scrolls to #stories section' },
  { id: 'TC-008', category: 'Landing Page', title: 'Verify Theme Toggle Switch (Dark/Light Mode)', target: 'nav button[title*="mode"]', expected: 'Toggles .dark class on <html>' },
  { id: 'TC-009', category: 'Landing Page', title: 'Verify Header "Sign in" Button Click', target: 'nav button:contains("Sign in")', expected: 'Opens AuthModal in signin view' },
  { id: 'TC-010', category: 'Landing Page', title: 'Verify Header "Join free" Button Click', target: 'nav button:contains("Join free")', expected: 'Opens AuthModal in signup view' },
  { id: 'TC-011', category: 'Hero Section', title: 'Verify Hero Main Title Visibility', target: 'h1', expected: 'Title containing "Swap Skills"' },
  { id: 'TC-012', category: 'Hero Section', title: 'Verify Hero Subtitle Content', target: 'p.hero-subtitle', expected: 'Explains skill exchange platform' },
  { id: 'TC-013', category: 'Hero Section', title: 'Verify Hero "Get Started Free" CTA Button', target: 'section.hero button:contains("Get Started")', expected: 'Opens AuthModal' },
  { id: 'TC-014', category: 'Hero Section', title: 'Verify Hero "Explore Skills" Secondary CTA Button', target: 'section.hero a:contains("Explore")', expected: 'Navigates to /explore' },
  { id: 'TC-015', category: 'Hero Section', title: 'Verify Hero Active Users Badge', target: '.badge-users', expected: 'Displays community stats' },
  { id: 'TC-016', category: 'Hero Section', title: 'Verify Hero Floating Skill Card 1 (React)', target: '.floating-card-1', expected: 'Displays React Developer tag' },
  { id: 'TC-017', category: 'Hero Section', title: 'Verify Hero Floating Skill Card 2 (UI Design)', target: '.floating-card-2', expected: 'Displays UI/UX Designer tag' },
  { id: 'TC-018', category: 'Hero Section', title: 'Verify Hero Trust Badges Rendering', target: '.trust-badges', expected: 'Renders trust icons' },
  { id: 'TC-019', category: 'Skill Marquee', title: 'Verify Marquee Infinite Scroll Banner', target: '.animate-scroll-marquee', expected: 'Renders continuous skill tags' },
  { id: 'TC-020', category: 'Skill Marquee', title: 'Verify Marquee Tag Click ("Python")', target: '.marquee-item:contains("Python")', expected: 'Highlight or search trigger' },
  { id: 'TC-021', category: 'Skill Marquee', title: 'Verify Marquee Tag Click ("UI/UX Design")', target: '.marquee-item:contains("UI")', expected: 'Highlight tag' },
  { id: 'TC-022', category: 'Skill Marquee', title: 'Verify Marquee Tag Click ("Data Science")', target: '.marquee-item:contains("Data")', expected: 'Highlight tag' },
  { id: 'TC-023', category: 'Skill Marquee', title: 'Verify Marquee Tag Click ("Spanish")', target: '.marquee-item:contains("Spanish")', expected: 'Highlight tag' },
  { id: 'TC-024', category: 'How It Works', title: 'Verify Section Header Title', target: '#how h2', expected: 'Title "How SkillSync Works"' },
  { id: 'TC-025', category: 'How It Works', title: 'Verify Step 1 Card ("Create Profile")', target: '.step-card-1', expected: 'Step 1 details displayed' },
  { id: 'TC-026', category: 'How It Works', title: 'Verify Step 2 Card ("Match & Connect")', target: '.step-card-2', expected: 'Step 2 details displayed' },
  { id: 'TC-027', category: 'How It Works', title: 'Verify Step 3 Card ("Swap Skills 1-on-1")', target: '.step-card-3', expected: 'Step 3 details displayed' },
  { id: 'TC-028', category: 'How It Works', title: 'Verify Interactive Demo Video Trigger Button', target: 'button.watch-demo', expected: 'Launches video modal' },
  { id: 'TC-029', category: 'Categories', title: 'Verify Category Section Header', target: '#skills h2', expected: 'Title "Browse Skill Categories"' },
  { id: 'TC-030', category: 'Categories', title: 'Verify Category Pill "Programming & Tech"', target: '.cat-pill:contains("Programming")', expected: 'Filters category skills' },
  { id: 'TC-031', category: 'Categories', title: 'Verify Category Pill "Design & Creative"', target: '.cat-pill:contains("Design")', expected: 'Filters category skills' },
  { id: 'TC-032', category: 'Categories', title: 'Verify Category Pill "Languages & Culture"', target: '.cat-pill:contains("Languages")', expected: 'Filters category skills' },
  { id: 'TC-033', category: 'Categories', title: 'Verify Category Pill "Music & Audio"', target: '.cat-pill:contains("Music")', expected: 'Filters category skills' },
  { id: 'TC-034', category: 'Categories', title: 'Verify Category Pill "Fitness & Wellness"', target: '.cat-pill:contains("Fitness")', expected: 'Filters category skills' },
  { id: 'TC-035', category: 'Categories', title: 'Verify Category Card "Join to Learn" Button', target: '.cat-card button:contains("Learn")', expected: 'Opens signup modal' },
  { id: 'TC-036', category: 'Categories', title: 'Verify Category Card "Join to Teach" Button', target: '.cat-card button:contains("Teach")', expected: 'Opens signup modal' },
  { id: 'TC-037', category: 'Stories', title: 'Verify Success Stories Header', target: '#stories h2', expected: 'Title "Community Success Stories"' },
  { id: 'TC-038', category: 'Stories', title: 'Verify Testimonial Card 1 (Alex & Sarah)', target: '.testimonial-1', expected: 'Renders story text & rating' },
  { id: 'TC-039', category: 'Stories', title: 'Verify Testimonial Card 2 (Marcus & Elena)', target: '.testimonial-2', expected: 'Renders story text & rating' },
  { id: 'TC-040', category: 'Stories', title: 'Verify Carousel Next Arrow Button', target: 'button.carousel-next', expected: 'Slides to next testimonial' },
  { id: 'TC-041', category: 'Stories', title: 'Verify Carousel Prev Arrow Button', target: 'button.carousel-prev', expected: 'Slides to previous testimonial' },
  { id: 'TC-042', category: 'CTA Section', title: 'Verify Call-To-Action Banner Title', target: '.cta-section h2', expected: 'Title "Ready to start swapping?"' },
  { id: 'TC-043', category: 'CTA Section', title: 'Verify CTA "Create Free Account" Button', target: '.cta-section button:contains("Create")', expected: 'Opens signup modal' },
  { id: 'TC-044', category: 'CTA Section', title: 'Verify CTA Guarantee Badge', target: '.cta-guarantee', expected: '100% Free Forever badge' },
  { id: 'TC-045', category: 'Footer', title: 'Verify Footer Brand Logo & Tagline', target: 'footer .footer-logo', expected: 'Renders footer brand' },
  { id: 'TC-046', category: 'Footer', title: 'Verify Footer "Explore" Quick Link', target: 'footer a[href="/explore"]', expected: 'Navigates to Explore' },
  { id: 'TC-047', category: 'Footer', title: 'Verify Footer "How it Works" Quick Link', target: 'footer a[href="/#how"]', expected: 'Scrolls to #how' },
  { id: 'TC-048', category: 'Footer', title: 'Verify Footer "AI Coach" Quick Link', target: 'footer a[href="/coach"]', expected: 'Navigates to AI Coach' },
  { id: 'TC-049', category: 'Footer', title: 'Verify Footer "Privacy Policy" Link', target: 'footer a:contains("Privacy")', expected: 'Opens Privacy terms' },
  { id: 'TC-050', category: 'Footer', title: 'Verify Footer "Terms of Service" Link', target: 'footer a:contains("Terms")', expected: 'Opens Terms modal' },
  { id: 'TC-051', category: 'Footer', title: 'Verify Footer Social Media Twitter Icon', target: 'footer a[title="Twitter"]', expected: 'Opens Twitter' },
  { id: 'TC-052', category: 'Footer', title: 'Verify Footer Social Media GitHub Icon', target: 'footer a[title="GitHub"]', expected: 'Opens GitHub' },
  { id: 'TC-053', category: 'Footer', title: 'Verify Footer Social Media LinkedIn Icon', target: 'footer a[title="LinkedIn"]', expected: 'Opens LinkedIn' },
  { id: 'TC-054', category: 'Footer', title: 'Verify Footer Copyright Text', target: 'footer .copyright', expected: 'Copyright © SkillSync' },
  { id: 'TC-055', category: 'Footer', title: 'Verify Back-To-Top Floating Button', target: 'button.back-to-top', expected: 'Scrolls viewport to top' },

  // ==========================================
  // MODULE B: AUTHENTICATION & ONBOARDING (TC-056 to TC-095)
  // ==========================================
  { id: 'TC-056', category: 'Auth Modal', title: 'Verify AuthModal Backdrop Click Close', target: '.auth-modal-overlay', expected: 'Closes modal overlay' },
  { id: 'TC-057', category: 'Auth Modal', title: 'Verify AuthModal Close (X) Button', target: '.auth-modal button.close-x', expected: 'Closes AuthModal' },
  { id: 'TC-058', category: 'Auth Modal', title: 'Verify Switch to "Create Account" Tab', target: '.auth-modal button:contains("Sign up")', expected: 'Switches view to signup' },
  { id: 'TC-059', category: 'Auth Modal', title: 'Verify Switch to "Sign In" Tab', target: '.auth-modal button:contains("Sign in")', expected: 'Switches view to signin' },
  { id: 'TC-060', category: 'Auth Modal', title: 'Verify "Email" Auth Method Button', target: '.auth-modal button:contains("Email")', expected: 'Displays Email form fields' },
  { id: 'TC-061', category: 'Auth Modal', title: 'Verify "Phone" Auth Method Button', target: '.auth-modal button:contains("Phone")', expected: 'Displays Phone form fields' },
  { id: 'TC-062', category: 'Auth Modal', title: 'Verify Email Input Field Focus & Typing', target: 'input[type="email"]', expected: 'Accepts email string' },
  { id: 'TC-063', category: 'Auth Modal', title: 'Verify Password Input Field Focus & Typing', target: 'input[type="password"]', expected: 'Accepts password string' },
  { id: 'TC-064', category: 'Auth Modal', title: 'Verify Password Visibility Toggle Button', target: '.auth-modal button.toggle-password', expected: 'Toggles type="text"' },
  { id: 'TC-065', category: 'Auth Modal', title: 'Verify Empty Form Submit Prevention', target: '.auth-modal button[type="submit"]', expected: 'Button disabled or shows error' },
  { id: 'TC-066', category: 'Auth Modal', title: 'Verify Invalid Email Validation Alert', target: 'input[type="email"]', expected: 'Triggers HTML5 / custom validation' },
  { id: 'TC-067', category: 'Auth Modal', title: 'Verify Short Password (<6 chars) Validation Alert', target: 'input[type="password"]', expected: 'Triggers password length warning' },
  { id: 'TC-068', category: 'Auth Modal', title: 'Verify Valid Credentials Fill (princeirfan282@gmail.com)', target: 'input[type="email"]', expected: 'Input populated successfully' },
  { id: 'TC-069', category: 'Auth Modal', title: 'Verify Password Fill (123user123)', target: 'input[type="password"]', expected: 'Password populated successfully' },
  { id: 'TC-070', category: 'Auth Modal', title: 'Verify Submit Auth Form Click', target: '.auth-modal button[type="submit"]', expected: 'Triggers Supabase sign-in' },
  { id: 'TC-071', category: 'Auth Modal', title: 'Verify Login Loading Spinner State', target: '.auth-modal .animate-spin', expected: 'Spinner active during API call' },
  { id: 'TC-072', category: 'Auth Modal', title: 'Verify Successful Auth Redirect', target: 'window.location', expected: 'Redirects user to /dashboard' },
  { id: 'TC-073', category: 'Auth Modal', title: 'Verify Forgot Password Link Click', target: '.auth-modal button:contains("Forgot")', expected: 'Opens password reset prompt' },
  { id: 'TC-074', category: 'Auth Modal', title: 'Verify Phone Country Code Selector', target: '.auth-modal select.country-code', expected: 'Allows selecting +91, +1, etc.' },
  { id: 'TC-075', category: 'Auth Modal', title: 'Verify Phone Input Field Typing', target: '.auth-modal input[type="tel"]', expected: 'Accepts mobile phone numbers' },
  { id: 'TC-076', category: 'Onboarding', title: 'Verify Onboarding Step 1 Title', target: '.onboarding h1', expected: 'Title "Welcome to SkillSync!"' },
  { id: 'TC-077', category: 'Onboarding', title: 'Verify Onboarding Step Indicator Bar (1/3)', target: '.onboarding .progress-bar-1', expected: 'Step 1 highlighted' },
  { id: 'TC-078', category: 'Onboarding', title: 'Verify Full Name Input Field Typing', target: '.onboarding input[placeholder*="Name"]', expected: 'Populates name string' },
  { id: 'TC-079', category: 'Onboarding', title: 'Verify Step 1 "Get Started" Button Disabled State', target: '.onboarding button:contains("Get Started")', expected: 'Disabled when name is empty' },
  { id: 'TC-080', category: 'Onboarding', title: 'Verify Step 1 "Get Started" Button Click', target: '.onboarding button:contains("Get Started")', expected: 'Advances to Step 2' },
  { id: 'TC-081', category: 'Onboarding', title: 'Verify Step 2 Title ("What can you teach?")', target: '.onboarding h1', expected: 'Step 2 header loaded' },
  { id: 'TC-082', category: 'Onboarding', title: 'Verify Step 2 Skill Pill Toggle Click (Skill 1)', target: '.onboarding button.skill-pill-1', expected: 'Highlights offering skill pill' },
  { id: 'TC-083', category: 'Onboarding', title: 'Verify Step 2 Skill Pill Toggle Click (Skill 2)', target: '.onboarding button.skill-pill-2', expected: 'Highlights offering skill pill' },
  { id: 'TC-084', category: 'Onboarding', title: 'Verify Step 2 Max Limit (3 Skills) Warning Alert', target: '.onboarding button.skill-pill-4', expected: 'Shows max 3 limit alert' },
  { id: 'TC-085', category: 'Onboarding', title: 'Verify Step 2 "Back" Button Click', target: '.onboarding button:contains("Back")', expected: 'Returns to Step 1' },
  { id: 'TC-086', category: 'Onboarding', title: 'Verify Step 2 "Next Step" Button Click', target: '.onboarding button:contains("Next Step")', expected: 'Advances to Step 3' },
  { id: 'TC-087', category: 'Onboarding', title: 'Verify Step 3 Title ("What do you want to learn?")', target: '.onboarding h1', expected: 'Step 3 header loaded' },
  { id: 'TC-088', category: 'Onboarding', title: 'Verify Step 3 Skill Pill Toggle Click (Seeking 1)', target: '.onboarding button.seeking-pill-1', expected: 'Highlights seeking skill pill' },
  { id: 'TC-089', category: 'Onboarding', title: 'Verify Step 3 Skill Pill Toggle Click (Seeking 2)', target: '.onboarding button.seeking-pill-2', expected: 'Highlights seeking skill pill' },
  { id: 'TC-090', category: 'Onboarding', title: 'Verify Setup Summary Box Generation', target: '.onboarding .summary-box', expected: 'Displays chosen name & skills' },
  { id: 'TC-091', category: 'Onboarding', title: 'Verify Step 3 "Back" Button Click', target: '.onboarding button:contains("Back")', expected: 'Returns to Step 2' },
  { id: 'TC-092', category: 'Onboarding', title: 'Verify Step 3 "Finish Setup" Button Click', target: '.onboarding button:contains("Finish Setup")', expected: 'Saves user skills to API' },
  { id: 'TC-093', category: 'Onboarding', title: 'Verify Setup Completion Loading Spinner', target: '.onboarding .animate-spin', expected: 'Renders spinner during save' },
  { id: 'TC-094', category: 'Onboarding', title: 'Verify Redirect to Dashboard After Setup', target: 'window.location', expected: 'Navigates to /dashboard' },
  { id: 'TC-095', category: 'Auth Session', title: 'Verify Auth Token Storage in LocalStorage', target: 'localStorage["sb-token"]', expected: 'Valid token present' },

  // ==========================================
  // MODULE C: DASHBOARD & HEADER FEATURES (TC-096 to TC-150)
  // ==========================================
  { id: 'TC-096', category: 'Dashboard Topbar', title: 'Verify Brand Logo Redirect in Dashboard Header', target: '.dashboard-topbar a.logo', expected: 'Keeps user on /dashboard' },
  { id: 'TC-097', category: 'Dashboard Topbar', title: 'Verify User Avatar Badge Rendering', target: '.dashboard-topbar .avatar-badge', expected: 'Displays user avatar/initials' },
  { id: 'TC-098', category: 'Dashboard Topbar', title: 'Verify Theme Switch Button in Dashboard', target: '.dashboard-topbar button[title*="mode"]', expected: 'Toggles dark/light mode' },
  { id: 'TC-099', category: 'Notifications', title: 'Verify Notification Bell Icon Button Click', target: 'button.notification-bell-btn', expected: 'Opens notification dropdown' },
  { id: 'TC-100', category: 'Notifications', title: 'Verify Notification Dropdown Header', target: '.notification-panel h3', expected: 'Title "Notifications"' },
  { id: 'TC-101', category: 'Notifications', title: 'Verify Notification Item Click (Mark as Read)', target: '.notification-item-unread', expected: 'Marks notification as read' },
  { id: 'TC-102', category: 'Notifications', title: 'Verify Notification Clear All Button Click', target: 'button.clear-notifications-btn', expected: 'Clears notification list' },
  { id: 'TC-103', category: 'Notifications', title: 'Verify Notification Panel Outside Click Close', target: '.dashboard-content', expected: 'Closes notification dropdown' },
  { id: 'TC-104', category: 'Dashboard Topbar', title: 'Verify Profile Icon Navigation Button', target: '.dashboard-topbar button.profile-nav-btn', expected: 'Navigates to /profile' },
  { id: 'TC-105', category: 'Dashboard Topbar', title: 'Verify Logout Topbar Icon Button Click', target: '.dashboard-topbar button.logout-btn', expected: 'Triggers sign-out' },
  { id: 'TC-106', category: 'Dashboard Hero', title: 'Verify Welcome Message Personalization', target: '.dashboard h1', expected: 'Greeting containing user name' },
  { id: 'TC-107', category: 'Dashboard Hero', title: 'Verify User Active Status Indicator', target: '.status-online', expected: 'Renders green online badge' },
  { id: 'TC-108', category: 'Dashboard Hero', title: 'Verify "Explore Skills" Primary Action Button', target: '.dashboard button:contains("Explore Skills")', expected: 'Navigates to /explore' },
  { id: 'TC-109', category: 'Dashboard Hero', title: 'Verify "Chat with Coach" Action Button', target: '.dashboard button:contains("Coach")', expected: 'Navigates to /coach' },
  { id: 'TC-110', category: 'Recommendations', title: 'Verify Recommendation Carousel Header', target: '.recs-section h2', expected: 'Title "Recommended Matches"' },
  { id: 'TC-111', category: 'Recommendations', title: 'Verify Recommended User Card 1 Display', target: '.rec-card-1', expected: 'Renders match profile' },
  { id: 'TC-112', category: 'Recommendations', title: 'Verify User Skill Tag Badges ("Teaches")', target: '.rec-card-1 .teaches-tag', expected: 'Displays skills taught' },
  { id: 'TC-113', category: 'Recommendations', title: 'Verify User Skill Tag Badges ("Wants")', target: '.rec-card-1 .wants-tag', expected: 'Displays skills wanted' },
  { id: 'TC-114', category: 'Recommendations', title: 'Verify Recommended User Rating Star Display', target: '.rec-card-1 .rating-stars', expected: 'Renders star rating score' },
  { id: 'TC-115', category: 'Recommendations', title: 'Verify Recommended Card 1 "Request Connection" Click', target: '.rec-card-1 button:contains("Request")', expected: 'Sends match request API' },
  { id: 'TC-116', category: 'Recommendations', title: 'Verify Request Connection Loading Spinner', target: '.rec-card-1 .animate-spin', expected: 'Displays spinner on button' },
  { id: 'TC-117', category: 'Recommendations', title: 'Verify "Request Sent" Button Disabled Feedback State', target: '.rec-card-1 button:contains("Sent")', expected: 'Changes button to green' },
  { id: 'TC-118', category: 'Recommendations', title: 'Verify Duplicate Connection Request Prevention', target: '.rec-card-1 button:contains("Sent")', expected: 'Button disabled' },
  { id: 'TC-119', category: 'Requests Section', title: 'Verify "Pending Requests" Section Header', target: '.pending-requests h2', expected: 'Title "Connection Requests"' },
  { id: 'TC-120', category: 'Requests Section', title: 'Verify Request Card Accept Button Click', target: '.request-card button.accept-btn', expected: 'Accepts match connection' },
  { id: 'TC-121', category: 'Requests Section', title: 'Verify Request Card Decline Button Click', target: '.request-card button.decline-btn', expected: 'Declines match request' },
  { id: 'TC-122', category: 'Requests Section', title: 'Verify Connection Status Badge Update', target: '.request-card .status-accepted', expected: 'Updates status to Connected' },
  { id: 'TC-123', category: 'Active Connections', title: 'Verify "Active Connections" Section Header', target: '.active-connections h2', expected: 'Title "My Connections"' },
  { id: 'TC-124', category: 'Active Connections', title: 'Verify Active Connection Card 1 Display', target: '.connection-card-1', expected: 'Displays connection avatar' },
  { id: 'TC-125', category: 'Active Connections', title: 'Verify Connection Card 1 "Message" Button Click', target: '.connection-card-1 button:contains("Message")', expected: 'Opens chat room in /messages' },
  { id: 'TC-126', category: 'Upcoming Sessions', title: 'Verify "Upcoming Sessions" Section Header', target: '.upcoming-sessions h2', expected: 'Title "Scheduled Swap Sessions"' },
  { id: 'TC-127', category: 'Upcoming Sessions', title: 'Verify Scheduled Session Card Date/Time Info', target: '.session-card .session-time', expected: 'Displays date and time' },
  { id: 'TC-128', category: 'Upcoming Sessions', title: 'Verify "Add to Cal" (Google Calendar) Link Click', target: '.session-card a:contains("Add to Cal")', expected: 'Opens Google Calendar tab' },
  { id: 'TC-129', category: 'Upcoming Sessions', title: 'Verify "Open Chat" Session Button Click', target: '.session-card button:contains("Open Chat")', expected: 'Navigates to chat thread' },
  { id: 'TC-130', category: 'AI Promotion Banner', title: 'Verify AI Coach Promotion Card in Dashboard', target: '.ai-coach-banner', expected: 'Renders AI Coach intro' },
  { id: 'TC-131', category: 'AI Promotion Banner', title: 'Verify AI Coach "Try Coach Gemini" Button Click', target: '.ai-coach-banner button:contains("Try")', expected: 'Navigates to /coach' },
  { id: 'TC-132', category: 'Mobile Nav', title: 'Verify Mobile Navigation Bar Rendering', target: '.md\\:hidden.fixed.bottom-0', expected: 'Fixed bottom bar visible' },
  { id: 'TC-133', category: 'Mobile Nav', title: 'Verify Mobile Nav "Home" Icon Button Click', target: 'button:contains("Home")', expected: 'Navigates to /dashboard' },
  { id: 'TC-134', category: 'Mobile Nav', title: 'Verify Mobile Nav "Explore" Icon Button Click', target: 'button:contains("Explore")', expected: 'Navigates to /explore' },
  { id: 'TC-135', category: 'Mobile Nav', title: 'Verify Mobile Nav "AI Coach" Icon Button Click', target: 'button:contains("AI Coach")', expected: 'Navigates to /coach' },
  { id: 'TC-136', category: 'Mobile Nav', title: 'Verify Mobile Nav "Messages" Icon Button Click', target: 'button:contains("Messages")', expected: 'Navigates to /messages' },
  { id: 'TC-137', category: 'Mobile Nav', title: 'Verify Mobile Nav "Profile" Icon Button Click', target: 'button:contains("Profile")', expected: 'Navigates to /profile' },
  { id: 'TC-138', category: 'Mobile Nav', title: 'Verify Mobile Nav Active Indicator Highlight', target: '.text-primary.scale-110', expected: 'Highlights active route tab' },
  { id: 'TC-139', category: 'Dashboard Skeleton', title: 'Verify Dashboard Loading Skeleton State', target: '.skeleton-loader', expected: 'Skeletons shown while loading' },
  { id: 'TC-140', category: 'Dashboard Error', title: 'Verify API Network Error Retry Button', target: 'button:contains("Retry")', expected: 'Retries data fetching' },
  { id: 'TC-141', category: 'Dashboard Stats', title: 'Verify Total Hours Swapped Counter Badge', target: '.stat-hours-swapped', expected: 'Displays numerical stats' },
  { id: 'TC-142', category: 'Dashboard Stats', title: 'Verify Completed Sessions Counter Badge', target: '.stat-sessions-completed', expected: 'Displays completed count' },
  { id: 'TC-143', category: 'Dashboard Stats', title: 'Verify Reputation Star Score Display', target: '.stat-reputation-score', expected: 'Displays star score' },
  { id: 'TC-144', category: 'Dashboard Quick Links', title: 'Verify Quick Action "Update Profile" Button', target: 'a:contains("Update Profile")', expected: 'Navigates to /profile' },
  { id: 'TC-145', category: 'Dashboard Quick Links', title: 'Verify Quick Action "Settings" Button', target: 'a:contains("Settings")', expected: 'Navigates to /settings' },
  { id: 'TC-146', category: 'Dashboard Search', title: 'Verify Topbar Search Input Typing', target: 'input[placeholder*="Search"]', expected: 'Accepts query string' },
  { id: 'TC-147', category: 'Dashboard Search', title: 'Verify Topbar Search Submit on Enter', target: 'input[placeholder*="Search"]', expected: 'Triggers search query' },
  { id: 'TC-148', category: 'Dashboard Activity', title: 'Verify Recent Activity Feed Items Rendering', target: '.activity-feed-item', expected: 'Renders activity logs' },
  { id: 'TC-149', category: 'Dashboard Refresh', title: 'Verify Pull-To-Refresh / Refresh Data Button', target: 'button.refresh-dashboard-btn', expected: 'Refreshes dashboard items' },
  { id: 'TC-150', category: 'Dashboard Footer', title: 'Verify Dashboard Footer Links & Version Badge', target: '.dashboard-footer', expected: 'SkillSync v1.0.0' },

  // ==========================================
  // MODULE D: EXPLORE & SKILL DISCOVERY (TC-151 to TC-200)
  // ==========================================
  { id: 'TC-151', category: 'Explore Header', title: 'Verify Explore Page Header Title', target: 'h1:contains("Explore")', expected: 'Displays Explore Skills' },
  { id: 'TC-152', category: 'Explore Header', title: 'Verify Back Arrow Button to Dashboard', target: 'button.back-arrow-btn', expected: 'Navigates back to /dashboard' },
  { id: 'TC-153', category: 'Explore Search', title: 'Verify Search Input Placeholder Text', target: 'input[placeholder*="Search skills"]', expected: 'Displays search placeholder' },
  { id: 'TC-154', category: 'Explore Search', title: 'Verify Search Input Typing ("React")', target: 'input[placeholder*="Search skills"]', expected: 'Populates "React"' },
  { id: 'TC-155', category: 'Explore Search', title: 'Verify Search Form "Search" Button Click', target: 'form button[type="submit"]', expected: 'Fetches matching users' },
  { id: 'TC-156', category: 'Explore Search', title: 'Verify Search Results Count Heading', target: 'h2:contains("Search Results")', expected: 'Displays count of matches' },
  { id: 'TC-157', category: 'Explore Search', title: 'Verify Search Clear Query Action', target: 'input[placeholder*="Search skills"]', expected: 'Clears search input' },
  { id: 'TC-158', category: 'Explore Filter', title: 'Verify City/Location Filter Input Typing ("New York")', target: 'input[placeholder*="Filter by city"]', expected: 'Filters users by NYC' },
  { id: 'TC-159', category: 'Explore Filter', title: 'Verify Sort Dropdown Open & Selection ("Rating")', target: 'select:has(option[value="rating"])', expected: 'Sorts results by avg rating' },
  { id: 'TC-160', category: 'Explore Filter', title: 'Verify Sort Dropdown Selection ("Newest")', target: 'select:has(option[value="newest"])', expected: 'Sorts results by created date' },
  { id: 'TC-161', category: 'Explore Category', title: 'Verify Category Chip "All" Selection Click', target: 'button.cat-chip:contains("All")', expected: 'Shows all user cards' },
  { id: 'TC-162', category: 'Explore Category', title: 'Verify Category Chip "Programming" Click', target: 'button.cat-chip:contains("Programming")', expected: 'Filters programming users' },
  { id: 'TC-163', category: 'Explore Category', title: 'Verify Category Chip "Design" Click', target: 'button.cat-chip:contains("Design")', expected: 'Filters design users' },
  { id: 'TC-164', category: 'Explore Category', title: 'Verify Category Chip "Languages" Click', target: 'button.cat-chip:contains("Languages")', expected: 'Filters language users' },
  { id: 'TC-165', category: 'Explore Category', title: 'Verify Category Chip "Music" Click', target: 'button.cat-chip:contains("Music")', expected: 'Filters music users' },
  { id: 'TC-166', category: 'Explore Category', title: 'Verify Category Chip "Art" Click', target: 'button.cat-chip:contains("Art")', expected: 'Filters art users' },
  { id: 'TC-167', category: 'Explore Category', title: 'Verify Category Chip "Cooking" Click', target: 'button.cat-chip:contains("Cooking")', expected: 'Filters cooking users' },
  { id: 'TC-168', category: 'Explore Category', title: 'Verify Category Chip "Fitness" Click', target: 'button.cat-chip:contains("Fitness")', expected: 'Filters fitness users' },
  { id: 'TC-169', category: 'Explore User Card', title: 'Verify User Card Avatar Image Rendering', target: '.user-card img.avatar', expected: 'Renders avatar image' },
  { id: 'TC-170', category: 'Explore User Card', title: 'Verify User Card Fallback Initial Avatar', target: '.user-card .avatar-initial', expected: 'Renders initial letter' },
  { id: 'TC-171', category: 'Explore User Card', title: 'Verify User Card Display Name Text', target: '.user-card h3', expected: 'Displays user full name' },
  { id: 'TC-172', category: 'Explore User Card', title: 'Verify User Card Location Pin & City Text', target: '.user-card .location-text', expected: 'Displays user location' },
  { id: 'TC-173', category: 'Explore User Card', title: 'Verify User Card Hidden Location Text', target: '.user-card:contains("Location hidden")', expected: 'Location hidden tag' },
  { id: 'TC-174', category: 'Explore User Card', title: 'Verify User Card Rating Badge Display', target: '.user-card .rating-badge', expected: 'Displays star score' },
  { id: 'TC-175', category: 'Explore User Card', title: 'Verify User Card Bio Paragraph', target: '.user-card p.bio', expected: 'Displays user bio snippet' },
  { id: 'TC-176', category: 'Explore User Card', title: 'Verify User Card Skill Tags ("They can teach you:")', target: '.user-card .teach-skills', expected: 'Renders skill pills' },
  { id: 'TC-177', category: 'Explore Action', title: 'Verify User Card "Request Connection" Button Click', target: '.user-card button:contains("Request Connection")', expected: 'Triggers request API' },
  { id: 'TC-178', category: 'Explore Action', title: 'Verify Connection Loading Spinner in Card', target: '.user-card .animate-spin', expected: 'Shows spinner during call' },
  { id: 'TC-179', category: 'Explore Action', title: 'Verify "Request Sent" Button State Update', target: '.user-card button:contains("Request Sent")', expected: 'Disables button with green background' },
  { id: 'TC-180', category: 'Explore Action', title: 'Verify Duplicate Request Alert Handling', target: '.user-card button:contains("Request Sent")', expected: 'Prevents multiple clicks' },
  { id: 'TC-181', category: 'Explore Empty State', title: 'Verify Empty Search Result Message Display', target: 'div:contains("No users found")', expected: 'Renders no-results view' },
  { id: 'TC-182', category: 'Explore Loading', title: 'Verify Explore Skeleton Loaders', target: '.card-skeleton', expected: 'Skeleton components visible' },
  { id: 'TC-183', category: 'Explore Pagination', title: 'Verify Next Page Pagination Button', target: 'button.pagination-next', expected: 'Loads next batch of users' },
  { id: 'TC-184', category: 'Explore Pagination', title: 'Verify Previous Page Pagination Button', target: 'button.pagination-prev', expected: 'Loads prev batch of users' },
  { id: 'TC-185', category: 'Explore Scroll', title: 'Verify Horizontal Scroll on Category Pills', target: '.no-scrollbar', expected: 'Scrolls categories horizontally' },
  { id: 'TC-186', category: 'Explore Card Hover', title: 'Verify User Card Hover Shadow Elevation Effect', target: '.user-card:hover', expected: 'Elevates box shadow' },
  { id: 'TC-187', category: 'Explore Skill Click', title: 'Verify Skill Chip Click Filters By That Skill', target: '.user-card span.skill-pill:first', expected: 'Auto-fills search query' },
  { id: 'TC-188', category: 'Explore Topbar', title: 'Verify Theme Toggle Button on Explore Page', target: '.dashboard-topbar button[title*="mode"]', expected: 'Toggles color mode' },
  { id: 'TC-189', category: 'Explore Topbar', title: 'Verify Notification Bell on Explore Page', target: '.dashboard-topbar .notification-bell', expected: 'Opens notifications' },
  { id: 'TC-190', category: 'Explore Topbar', title: 'Verify Profile Link Button on Explore Page', target: '.dashboard-topbar button[title*="Profile"]', expected: 'Navigates to /profile' },
  { id: 'TC-191', category: 'Explore Topbar', title: 'Verify Sign Out Button on Explore Page', target: '.dashboard-topbar button[title*="Sign Out"]', expected: 'Triggers sign out' },
  { id: 'TC-192', category: 'Explore Filter Reset', title: 'Verify Reset Filters Clear Button', target: 'button.reset-filters-btn', expected: 'Resets search & filters' },
  { id: 'TC-193', category: 'Explore City Clear', title: 'Verify Clear City Filter Field Action', target: 'input[placeholder*="Filter by city"]', expected: 'Resets location filter' },
  { id: 'TC-194', category: 'Explore Search Submit', title: 'Verify Search Submit on Enter Keypress', target: 'input[placeholder*="Search skills"]', expected: 'Submits search on Enter' },
  { id: 'TC-195', category: 'Explore Card Count', title: 'Verify Count Badge Matches Rendered Cards', target: '.results-count-badge', expected: 'Count matches DOM card total' },
  { id: 'TC-196', category: 'Explore Card Rating', title: 'Verify Rating Star Icon Hover Tooltip', target: '.user-card .rating-badge:hover', expected: 'Shows rating breakdown' },
  { id: 'TC-197', category: 'Explore Skill Limit', title: 'Verify Skill List Truncation Tag (+2 more)', target: '.user-card .more-skills-badge', expected: 'Renders overflow skill count' },
  { id: 'TC-198', category: 'Explore Responsive', title: 'Verify Responsive Grid Layout (1 col mobile, 2 col desktop)', target: '.grid.md\\:grid-cols-2', expected: 'Renders 2 columns on desktop' },
  { id: 'TC-199', category: 'Explore Refresh', title: 'Verify Explore Page Soft Refresh Action', target: 'button.refresh-explore-btn', expected: 'Re-fetches user list' },
  { id: 'TC-200', category: 'Explore Bottom', title: 'Verify Mobile Navigation Bar Clearance on Explore', target: '.pb-28', expected: 'Page padded bottom 28' },

  // ==========================================
  // MODULE E: MESSAGES & MULTI-TAB WORKFLOW (TC-201 to TC-250)
  // ==========================================
  { id: 'TC-201', category: 'Messages UI', title: 'Verify Messages Page Container Layout', target: '.messages-container', expected: 'Renders sidebar & chat window' },
  { id: 'TC-202', category: 'Messages Sidebar', title: 'Verify Messages Sidebar Header Title', target: '.sidebar h2:contains("Messages")', expected: 'Displays Messages header' },
  { id: 'TC-203', category: 'Messages Sidebar', title: 'Verify Active Connections Search Bar Input', target: '.sidebar input[placeholder*="Search conversations"]', expected: 'Accepts search string' },
  { id: 'TC-204', category: 'Messages Sidebar', title: 'Verify Conversation Item 1 Selection Click', target: '.conversation-item-1', expected: 'Opens active chat window' },
  { id: 'TC-205', category: 'Messages Sidebar', title: 'Verify Selected Conversation Highlight Style', target: '.conversation-item-1.bg-muted', expected: 'Highlights selected item' },
  { id: 'TC-206', category: 'Messages Sidebar', title: 'Verify Conversation Item Avatar Rendering', target: '.conversation-item-1 img.avatar', expected: 'Displays partner avatar' },
  { id: 'TC-207', category: 'Messages Sidebar', title: 'Verify Conversation Item Online Status Dot', target: '.conversation-item-1 .online-dot', expected: 'Renders green dot' },
  { id: 'TC-208', category: 'Messages Sidebar', title: 'Verify Conversation Item Unread Counter Badge', target: '.conversation-item-1 .unread-badge', expected: 'Displays unread message count' },
  { id: 'TC-209', category: 'Chat Header', title: 'Verify Active Chat Partner Name Display', target: '.chat-header h3', expected: 'Displays chat partner name' },
  { id: 'TC-210', category: 'Chat Header', title: 'Verify Active Chat Partner Skill Badges', target: '.chat-header .partner-skills', expected: 'Displays skills partner teaches' },
  { id: 'TC-211', category: 'Chat Header', title: 'Verify Start Video Call Button Click', target: 'button.video-call-btn', expected: 'Launches Jitsi video modal' },
  { id: 'TC-212', category: 'Video Calling', title: 'Verify Jitsi Video Call Modal Open', target: '.jitsi-container iframe', expected: 'Renders Jitsi video iframe' },
  { id: 'TC-213', category: 'Video Calling', title: 'Verify End Video Call Button Click', target: 'button.end-video-call-btn', expected: 'Closes video call iframe modal' },
  { id: 'TC-214', category: 'Chat Header', title: 'Verify "Schedule Session" Button Click', target: 'button.schedule-session-btn', expected: 'Opens ScheduleModal dialog' },
  { id: 'TC-215', category: 'Schedule Modal', title: 'Verify Schedule Modal Header Title', target: '.schedule-modal h2', expected: 'Title "Schedule Skill Swap"' },
  { id: 'TC-216', category: 'Schedule Modal', title: 'Verify Schedule Modal Date Input Picker', target: '.schedule-modal input[type="date"]', expected: 'Allows date selection' },
  { id: 'TC-217', category: 'Schedule Modal', title: 'Verify Schedule Modal Time Input Picker', target: '.schedule-modal input[type="time"]', expected: 'Allows time selection' },
  { id: 'TC-218', category: 'Schedule Modal', title: 'Verify Schedule Modal Duration Selector', target: '.schedule-modal select.duration', expected: 'Selects 30m, 60m, 90m' },
  { id: 'TC-219', category: 'Schedule Modal', title: 'Verify Schedule Modal "Propose Session" Click', target: '.schedule-modal button:contains("Propose")', expected: 'Sends session proposal in chat' },
  { id: 'TC-220', category: 'Schedule Modal', title: 'Verify Schedule Modal Close Button Click', target: '.schedule-modal button.close-btn', expected: 'Closes ScheduleModal' },
  { id: 'TC-221', category: 'Chat Proposed Session', title: 'Verify Session Proposal Banner in Chat Bubble', target: '.chat-bubble.session-proposal', expected: 'Renders proposed session details' },
  { id: 'TC-222', category: 'Chat Proposed Session', title: 'Verify Proposal "Accept" Button Click', target: '.session-proposal button:contains("Accept")', expected: 'Updates proposal to Confirmed' },
  { id: 'TC-223', category: 'Chat Proposed Session', title: 'Verify Proposal "Decline" Button Click', target: '.session-proposal button:contains("Decline")', expected: 'Updates proposal to Declined' },
  { id: 'TC-224', category: 'Chat Header', title: 'Verify "Leave Review" Button Click', target: 'button.leave-review-btn', expected: 'Opens ReviewModal dialog' },
  { id: 'TC-225', category: 'Review Modal', title: 'Verify Review Modal Header Title', target: '.review-modal h2', expected: 'Title "Leave a Review"' },
  { id: 'TC-226', category: 'Review Modal', title: 'Verify Interactive Star Rating Click (5 Stars)', target: '.review-modal .star-5', expected: 'Highlights 5 stars yellow' },
  { id: 'TC-227', category: 'Review Modal', title: 'Verify Review Comment Textarea Typing', target: '.review-modal textarea', expected: 'Accepts review comment text' },
  { id: 'TC-228', category: 'Review Modal', title: 'Verify Review Submit Button Click', target: '.review-modal button:contains("Submit")', expected: 'Saves review to Supabase' },
  { id: 'TC-229', category: 'Review Modal', title: 'Verify Review Modal Close Button', target: '.review-modal button.close-btn', expected: 'Closes ReviewModal' },
  { id: 'TC-230', category: 'Chat Feed', title: 'Verify Message List Scroll Container', target: '.messages-feed', expected: 'Scrolls past messages' },
  { id: 'TC-231', category: 'Chat Feed', title: 'Verify Outgoing Message Bubble Styling (Primary Bg)', target: '.chat-bubble.sent', expected: 'Renders primary background bubble' },
  { id: 'TC-232', category: 'Chat Feed', title: 'Verify Incoming Message Bubble Styling (Muted Bg)', target: '.chat-bubble.received', expected: 'Renders muted background bubble' },
  { id: 'TC-233', category: 'Chat Feed', title: 'Verify Message Timestamp Rendering', target: '.chat-bubble .timestamp', expected: 'Displays time e.g. 10:45 AM' },
  { id: 'TC-234', category: 'Chat Feed', title: 'Verify Message Sent Read Receipt Checkmark (Check)', target: '.chat-bubble .icon-check', expected: 'Single checkmark icon visible' },
  { id: 'TC-235', category: 'Chat Feed', title: 'Verify Message Read Receipt Double Checkmark (CheckCheck)', target: '.chat-bubble .icon-check-check', expected: 'Double blue checkmark visible' },
  { id: 'TC-236', category: 'Chat Input', title: 'Verify Message Text Input Field Placeholder', target: 'input[placeholder*="Type a message"]', expected: 'Displays message placeholder' },
  { id: 'TC-237', category: 'Chat Input', title: 'Verify Message Text Typing ("Hello! Looking forward to our swap.")', target: 'input[placeholder*="Type a message"]', expected: 'Populates message text' },
  { id: 'TC-238', category: 'Chat Input', title: 'Verify Send Message Button Click', target: 'form.chat-form button[type="submit"]', expected: 'Appends message & calls API' },
  { id: 'TC-239', category: 'Chat Input', title: 'Verify Send Message on Enter Keypress', target: 'input[placeholder*="Type a message"]', expected: 'Sends message on Enter key' },
  { id: 'TC-240', category: 'Chat Input', title: 'Verify Auto-Scroll to Bottom on New Message', target: '.messages-feed-end', expected: 'Scrolls smoothly to bottom' },

  // MULTI-TAB WORKFLOW VERIFICATION (TC-241 to TC-250)
  { id: 'TC-241', category: 'Multi-Tab Workflow', title: 'Initialize Multi-Tab Session Context (Tab 1 & Tab 2)', target: 'browser.newTab()', expected: 'Tab 1 and Tab 2 active simultaneously' },
  { id: 'TC-242', category: 'Multi-Tab Workflow', title: 'Verify Auth State Synchronization Across Multiple Tabs', target: 'Tab 2 window.location', expected: 'Tab 2 authenticated automatically' },
  { id: 'TC-243', category: 'Multi-Tab Workflow', title: 'Send Message in Tab 1 ("Tab 1 test message")', target: 'Tab 1 chat-form', expected: 'Message sent in Tab 1' },
  { id: 'TC-244', category: 'Multi-Tab Workflow', title: 'Verify Real-Time Message Receipt in Tab 2', target: 'Tab 2 messages-feed', expected: 'Message appears instantly in Tab 2' },
  { id: 'TC-245', category: 'Multi-Tab Workflow', title: 'Reply to Message in Tab 2 ("Tab 2 response message")', target: 'Tab 2 chat-form', expected: 'Message sent from Tab 2' },
  { id: 'TC-246', category: 'Multi-Tab Workflow', title: 'Verify Real-Time Response Receipt in Tab 1', target: 'Tab 1 messages-feed', expected: 'Tab 2 response appears in Tab 1' },
  { id: 'TC-247', category: 'Multi-Tab Workflow', title: 'Propose Session in Tab 1', target: 'Tab 1 schedule-modal', expected: 'Session proposal sent in Tab 1' },
  { id: 'TC-248', category: 'Multi-Tab Workflow', title: 'Verify Real-Time Proposal Banner Appearance in Tab 2', target: 'Tab 2 session-proposal', expected: 'Proposal banner rendered in Tab 2' },
  { id: 'TC-249', category: 'Multi-Tab Workflow', title: 'Accept Session Proposal in Tab 2', target: 'Tab 2 proposal-accept-btn', expected: 'Session accepted in Tab 2' },
  { id: 'TC-250', category: 'Multi-Tab Workflow', title: 'Verify Session Status Update Syncs to Tab 1 (Confirmed)', target: 'Tab 1 proposal-status', expected: 'Tab 1 displays Confirmed status' },

  // ==========================================
  // MODULE F: AI CAREER COACH & ROADMAP GENERATOR (TC-251 to TC-285)
  // ==========================================
  { id: 'TC-251', category: 'AI Coach Header', title: 'Verify AI Coach Page Header Title', target: 'h1:contains("AI Career Coach")', expected: 'Title "AI Career Coach"' },
  { id: 'TC-252', category: 'AI Coach Header', title: 'Verify Coach Sparkles Icon Animation', target: 'svg.animate-pulse', expected: 'Renders animated sparkles icon' },
  { id: 'TC-253', category: 'AI Coach Header', title: 'Verify Back Arrow Button to Dashboard', target: 'button.back-arrow-btn', expected: 'Navigates back to /dashboard' },
  { id: 'TC-254', category: 'Skill Assessment', title: 'Verify "Skill Assessment" Card Title', target: 'h2:contains("Skill Assessment")', expected: 'Renders Skill Assessment box' },
  { id: 'TC-255', category: 'Skill Assessment', title: 'Verify "My Superpowers (Offering)" Badges', target: '.offering-skills-box .skill-chip', expected: 'Displays user offering skills' },
  { id: 'TC-256', category: 'Skill Assessment', title: 'Verify "My Targets (Seeking)" Badges', target: '.seeking-skills-box .skill-chip', expected: 'Displays user seeking skills' },
  { id: 'TC-257', category: 'Market Trend', title: 'Verify "Market Trend" Card Display', target: 'h2:contains("Market Trend")', expected: 'Renders market statistics' },
  { id: 'TC-258', category: 'Market Trend', title: 'Verify Demand Progress Bar ("Development")', target: '.progress-bar-dev', expected: 'Width 85% rendered' },
  { id: 'TC-259', category: 'Market Trend', title: 'Verify Demand Progress Bar ("Design & Creative")', target: '.progress-bar-design', expected: 'Width 60% rendered' },
  { id: 'TC-260', category: 'Coach Chat', title: 'Verify Coach Gemini Welcome Message', target: '.chat-box .welcome-msg', expected: 'Displays welcome coach prompt' },
  { id: 'TC-261', category: 'Coach Chat', title: 'Verify Quick-Reply Chip 1 ("🔍 Skill Gaps")', target: 'button:contains("Skill Gaps")', expected: 'Fills query into chat input' },
  { id: 'TC-262', category: 'Coach Chat', title: 'Verify Quick-Reply Chip 2 ("🤝 Prep Swap Session")', target: 'button:contains("Prep Swap")', expected: 'Fills query into chat input' },
  { id: 'TC-263', category: 'Coach Chat', title: 'Verify Quick-Reply Chip 3 ("📅 Roadmap Tips")', target: 'button:contains("Roadmap Tips")', expected: 'Fills query into chat input' },
  { id: 'TC-264', category: 'Coach Chat', title: 'Verify Custom Question Typing ("What skills should I learn next?")', target: 'input[placeholder*="Coach Gemini"]', expected: 'Accepts query text' },
  { id: 'TC-265', category: 'Coach Chat', title: 'Verify Send Question Button Click', target: 'form.coach-form button[type="submit"]', expected: 'Sends query to AI Coach' },
  { id: 'TC-266', category: 'Coach Chat', title: 'Verify AI Typing Bouncing Indicator Dots', target: '.animate-bounce', expected: 'Displays animated typing dots' },
  { id: 'TC-267', category: 'Coach Chat', title: 'Verify AI Coach Response Rendering', target: '.chat-box .coach-reply', expected: 'Renders structured AI advice' },
  { id: 'TC-268', category: 'Coach Chat', title: 'Verify Clear Conversation History Button Click', target: 'button[title="Clear Conversation"]', expected: 'Resets coach message list' },
  { id: 'TC-269', category: 'Roadmap Gen', title: 'Verify "Roadmap Generator" Panel Header', target: 'h2:contains("Roadmap Generator")', expected: 'Title "Roadmap Generator"' },
  { id: 'TC-270', category: 'Roadmap Gen', title: 'Verify Target Skill Dropdown Selector Focus', target: 'select.skill-roadmap-select', expected: 'Opens skill dropdown options' },
  { id: 'TC-271', category: 'Roadmap Gen', title: 'Verify Selecting Target Skill Option', target: 'select.skill-roadmap-select option:first', expected: 'Selects skill for roadmap' },
  { id: 'TC-272', category: 'Roadmap Gen', title: 'Verify "Generate Study Roadmap" Button Click', target: 'button:contains("Generate Study Roadmap")', expected: 'Generates 4-phase learning plan' },
  { id: 'TC-273', category: 'Roadmap Gen', title: 'Verify Generated Roadmap Title Card', target: '.roadmap-card h3', expected: 'Title "Roadmap: [Skill]"' },
  { id: 'TC-274', category: 'Roadmap Gen', title: 'Verify Roadmap Progress Percentage Badge (0%)', target: '.roadmap-progress-badge', expected: 'Displays "0% Done"' },
  { id: 'TC-275', category: 'Roadmap Gen', title: 'Verify Roadmap Step 1 Phase Card ("Foundational Core")', target: '.roadmap-step-1', expected: 'Renders Step 1 description' },
  { id: 'TC-276', category: 'Roadmap Gen', title: 'Verify Step 1 Completion Checkbox Click', target: '.roadmap-step-1 .checkbox', expected: 'Toggles Step 1 checked' },
  { id: 'TC-277', category: 'Roadmap Gen', title: 'Verify Progress Bar Update After Step 1 Check (25%)', target: '.roadmap-progress-badge', expected: 'Updates badge to "25% Done"' },
  { id: 'TC-278', category: 'Roadmap Gen', title: 'Verify Step 2 Completion Checkbox Click', target: '.roadmap-step-2 .checkbox', expected: 'Toggles Step 2 checked' },
  { id: 'TC-279', category: 'Roadmap Gen', title: 'Verify Progress Bar Update After Step 2 Check (50%)', target: '.roadmap-progress-badge', expected: 'Updates badge to "50% Done"' },
  { id: 'TC-280', category: 'Roadmap Gen', title: 'Verify Step 3 Completion Checkbox Click', target: '.roadmap-step-3 .checkbox', expected: 'Toggles Step 3 checked' },
  { id: 'TC-281', category: 'Roadmap Gen', title: 'Verify Progress Bar Update After Step 3 Check (75%)', target: '.roadmap-progress-badge', expected: 'Updates badge to "75% Done"' },
  { id: 'TC-282', category: 'Roadmap Gen', title: 'Verify Step 4 Completion Checkbox Click', target: '.roadmap-step-4 .checkbox', expected: 'Toggles Step 4 checked' },
  { id: 'TC-283', category: 'Roadmap Gen', title: 'Verify Progress Bar Update After All Checked (100%)', target: '.roadmap-progress-badge', expected: 'Updates badge to "100% Done"' },
  { id: 'TC-284', category: 'Roadmap Gen', title: 'Verify Unchecking Step Decrements Progress Bar', target: '.roadmap-step-4 .checkbox', expected: 'Decrements badge to "75% Done"' },
  { id: 'TC-285', category: 'AI Coach Responsive', title: 'Verify Mobile Layout Padding on AI Coach Page', target: '.pb-28', expected: 'Applies bottom padding 28' },

  // ==========================================
  // MODULE G: USER PROFILE & PORTFOLIO MANAGEMENT (TC-286 to TC-320)
  // ==========================================
  { id: 'TC-286', category: 'Profile Header', title: 'Verify Edit Profile Header Title', target: 'h1:contains("Edit Profile")', expected: 'Title "Edit Profile"' },
  { id: 'TC-287', category: 'Profile Header', title: 'Verify Header Back Arrow Button to Dashboard', target: 'button.back-arrow-btn', expected: 'Navigates back to /dashboard' },
  { id: 'TC-288', category: 'Profile Header', title: 'Verify Header "Save" Button Click', target: 'button:contains("Save")', expected: 'Triggers profile update API' },
  { id: 'TC-289', category: 'Profile Header', title: 'Verify Save Loading Spinner State', target: 'button:contains("Save") .animate-spin', expected: 'Displays spinner while saving' },
  { id: 'TC-290', category: 'Avatar Upload', title: 'Verify Profile Avatar Image Element', target: '.avatar-box img', expected: 'Renders avatar image' },
  { id: 'TC-291', category: 'Avatar Upload', title: 'Verify Camera Overlay Hover Effect', target: '.avatar-box label.cursor-pointer', expected: 'Shows camera icon overlay' },
  { id: 'TC-292', category: 'Avatar Upload', title: 'Verify File Input Field Trigger for Avatar', target: 'input[type="file"][accept*="image"]', expected: 'Opens system file picker' },
  { id: 'TC-293', category: 'Profile Basic', title: 'Verify "Display Name" Input Field Typing', target: 'input[placeholder="Your Name"]', expected: 'Populates name string' },
  { id: 'TC-294', category: 'Profile Basic', title: 'Verify "Bio" Textarea Typing', target: 'textarea[placeholder*="passionate about"]', expected: 'Populates bio string' },
  { id: 'TC-295', category: 'Profile Basic', title: 'Verify "Location" Input Field Typing', target: 'input[placeholder="City, Country"]', expected: 'Populates location string' },
  { id: 'TC-296', category: 'Privacy Settings', title: 'Verify "Public Profile" Toggle Checkbox Click', target: 'input[type="checkbox"].peer:first', expected: 'Toggles is_public boolean' },
  { id: 'TC-297', category: 'Privacy Settings', title: 'Verify "Show Location" Toggle Checkbox Click', target: 'input[type="checkbox"].peer:last', expected: 'Toggles show_location boolean' },
  { id: 'TC-298', category: 'Manage Skills', title: 'Verify "What I can teach" Section Title', target: 'h3:contains("What I can teach")', expected: 'Displays teaching header' },
  { id: 'TC-299', category: 'Manage Skills', title: 'Verify "Add" Offering Skill Button Click', target: 'button:contains("Add"):first', expected: 'Opens available skills dropdown' },
  { id: 'TC-300', category: 'Manage Skills', title: 'Verify Selecting Skill to Add (Offering)', target: '.offering-dropdown button.skill-opt:first', expected: 'Appends skill tag to offering list' },
  { id: 'TC-301', category: 'Manage Skills', title: 'Verify Removing Skill Pill (X Button)', target: '.offering-list button.remove-skill-btn:first', expected: 'Removes skill tag' },
  { id: 'TC-302', category: 'Manage Skills', title: 'Verify "What I want to learn" Section Title', target: 'h3:contains("What I want to learn")', expected: 'Displays learning header' },
  { id: 'TC-303', category: 'Manage Skills', title: 'Verify "Add" Seeking Skill Button Click', target: 'button:contains("Add"):last', expected: 'Opens available seeking list' },
  { id: 'TC-304', category: 'Manage Skills', title: 'Verify Selecting Skill to Add (Seeking)', target: '.seeking-dropdown button.skill-opt:first', expected: 'Appends skill tag to seeking list' },
  { id: 'TC-305', category: 'Manage Skills', title: 'Verify Removing Seeking Skill Pill (X Button)', target: '.seeking-list button.remove-skill-btn:first', expected: 'Removes seeking skill tag' },
  { id: 'TC-306', category: 'Portfolio', title: 'Verify "My Portfolio" Section Header', target: 'h2:contains("My Portfolio")', expected: 'Displays Portfolio title' },
  { id: 'TC-307', category: 'Portfolio', title: 'Verify "Add Project" Button Click', target: 'button:contains("Add Project")', expected: 'Opens PortfolioModal dialog' },
  { id: 'TC-308', category: 'Portfolio Modal', title: 'Verify Portfolio Modal Header Title', target: '.portfolio-modal h2', expected: 'Title "Add Project"' },
  { id: 'TC-309', category: 'Portfolio Modal', title: 'Verify Project Title Input Field Typing', target: '.portfolio-modal input[placeholder*="Title"]', expected: 'Populates title string' },
  { id: 'TC-310', category: 'Portfolio Modal', title: 'Verify Description Textarea Typing', target: '.portfolio-modal textarea[placeholder*="Description"]', expected: 'Populates description text' },
  { id: 'TC-311', category: 'Portfolio Modal', title: 'Verify Project Link Input Field Typing', target: '.portfolio-modal input[type="url"]', expected: 'Populates GitHub/live link' },
  { id: 'TC-312', category: 'Portfolio Modal', title: 'Verify "Add to Portfolio" Submit Button Click', target: '.portfolio-modal button:contains("Add to Portfolio")', expected: 'Saves project to portfolio' },
  { id: 'TC-313', category: 'Portfolio Modal', title: 'Verify Portfolio Modal Close (X) Button', target: '.portfolio-modal button.close-x', expected: 'Closes PortfolioModal' },
  { id: 'TC-314', category: 'Portfolio List', title: 'Verify Rendered Portfolio Card Title', target: '.portfolio-card h3', expected: 'Displays project title' },
  { id: 'TC-315', category: 'Portfolio List', title: 'Verify Portfolio External Link Button Click', target: '.portfolio-card a.external-link', expected: 'Opens project URL in new tab' },
  { id: 'TC-316', category: 'Portfolio List', title: 'Verify Portfolio Delete Project Trash Icon Click', target: '.portfolio-card button.delete-project-btn', expected: 'Deletes portfolio item' },
  { id: 'TC-317', category: 'Reviews Section', title: 'Verify "Reviews" Section Header & Average Rating Badge', target: 'h2:contains("Reviews")', expected: 'Displays rating score badge' },
  { id: 'TC-318', category: 'Reviews Section', title: 'Verify Review Card Reviewer Name & Date Display', target: '.review-card .reviewer-name', expected: 'Displays reviewer name' },
  { id: 'TC-319', category: 'Reviews Section', title: 'Verify Review Card Star Rating Score & Comment Text', target: '.review-card .star-rating', expected: 'Displays 5-star score & comment' },
  { id: 'TC-320', category: 'Profile Notification', title: 'Verify Notification Bell on Profile Page Header', target: '.dashboard-topbar .notification-bell', expected: 'Opens notification dropdown' },

  // ==========================================
  // MODULE H: SETTINGS & ACCOUNT SECURITY (TC-321 to TC-350)
  // ==========================================
  { id: 'TC-321', category: 'Settings Header', title: 'Verify Settings Page Header Title', target: 'h1:contains("Settings")', expected: 'Title "Settings"' },
  { id: 'TC-322', category: 'Settings Header', title: 'Verify Settings Back Chevron Button', target: 'button.back-chevron-btn', expected: 'Navigates back to previous page' },
  { id: 'TC-323', category: 'Privacy Section', title: 'Verify Privacy Section Title', target: 'h2:contains("Privacy & Visibility")', expected: 'Displays Privacy section' },
  { id: 'TC-324', category: 'Privacy Section', title: 'Verify "Public Profile" Switch Toggle Click', target: 'button.privacy-toggle-public', expected: 'Toggles public profile state' },
  { id: 'TC-325', category: 'Privacy Section', title: 'Verify "Show Location" Switch Toggle Click', target: 'button.privacy-toggle-location', expected: 'Toggles location display state' },
  { id: 'TC-326', category: 'Account Section', title: 'Verify Account Section Title', target: 'h2:contains("Account")', expected: 'Displays Account section' },
  { id: 'TC-327', category: 'Account Section', title: 'Verify "Email Address" Row Click', target: 'button.account-row-email', expected: 'Opens Update Email Modal' },
  { id: 'TC-328', category: 'Update Email Modal', title: 'Verify Update Email Modal Header Title', target: '.email-modal h3', expected: 'Title "Update Email Address"' },
  { id: 'TC-329', category: 'Update Email Modal', title: 'Verify New Email Input Field Typing', target: '.email-modal input[type="email"]', expected: 'Accepts new email address' },
  { id: 'TC-330', category: 'Update Email Modal', title: 'Verify "Update Email" Submit Button Click', target: '.email-modal button[type="submit"]', expected: 'Triggers Supabase email update' },
  { id: 'TC-331', category: 'Update Email Modal', title: 'Verify Update Email Modal Close Button', target: '.email-modal button.close-btn', expected: 'Closes email modal' },
  { id: 'TC-332', category: 'Account Section', title: 'Verify "Security / Password" Row Click', target: 'button.account-row-password', expected: 'Opens Update Password Modal' },
  { id: 'TC-333', category: 'Update Password Modal', title: 'Verify Update Password Modal Header Title', target: '.password-modal h3', expected: 'Title "Update Password"' },
  { id: 'TC-334', category: 'Update Password Modal', title: 'Verify New Password Input Typing', target: '.password-modal input[type="password"]', expected: 'Accepts new password string' },
  { id: 'TC-335', category: 'Update Password Modal', title: 'Verify Password Length Minimum 6 Chars Validation', target: '.password-modal button[type="submit"]', expected: 'Disabled if password < 6 chars' },
  { id: 'TC-336', category: 'Update Password Modal', title: 'Verify "Update Password" Submit Button Click', target: '.password-modal button[type="submit"]', expected: 'Triggers Supabase password update' },
  { id: 'TC-337', category: 'Update Password Modal', title: 'Verify Success Toast Notification Banner', target: '.toast-success', expected: 'Password updated successfully' },
  { id: 'TC-338', category: 'Update Password Modal', title: 'Verify Update Password Modal Close Button', target: '.password-modal button.close-btn', expected: 'Closes password modal' },
  { id: 'TC-339', category: 'Notifications Section', title: 'Verify "Alert Preferences" Row Click', target: 'button.notifications-row', expected: 'Opens "Coming Soon" Modal' },
  { id: 'TC-340', category: 'Coming Soon Modal', title: 'Verify Coming Soon Modal Title', target: '.coming-soon-modal h3', expected: 'Title "Coming Soon!"' },
  { id: 'TC-341', category: 'Coming Soon Modal', title: 'Verify Coming Soon "Got it" Button Click', target: '.coming-soon-modal button:contains("Got it")', expected: 'Closes coming soon modal' },
  { id: 'TC-342', category: 'Logout Button', title: 'Verify Red "Sign Out" Settings Button Click', target: 'button:contains("Sign Out")', expected: 'Triggers Supabase sign out' },
  { id: 'TC-343', category: 'Logout Button', title: 'Verify Sign Out Clears Auth LocalStorage', target: 'localStorage["sb-token"]', expected: 'Clears auth tokens' },
  { id: 'TC-344', category: 'Logout Redirect', title: 'Verify Redirect to Landing Page After Sign Out', target: 'window.location', expected: 'Navigates user to /' },
  { id: 'TC-345', category: 'Settings Version', title: 'Verify Footer Version String Rendering', target: 'p:contains("SkillSync v1.0.0")', expected: 'SkillSync v1.0.0 rendered' },
  { id: 'TC-346', category: 'Protected Routes', title: 'Verify Unauthenticated Access to /dashboard Redirects to /', target: 'window.location', expected: 'Redirects to landing page' },
  { id: 'TC-347', category: 'Protected Routes', title: 'Verify Unauthenticated Access to /messages Redirects to /', target: 'window.location', expected: 'Redirects to landing page' },
  { id: 'TC-348', category: 'Protected Routes', title: 'Verify Unauthenticated Access to /coach Redirects to /', target: 'window.location', expected: 'Redirects to landing page' },
  { id: 'TC-349', category: 'Protected Routes', title: 'Verify Unauthenticated Access to /profile Redirects to /', target: 'window.location', expected: 'Redirects to landing page' },
  { id: 'TC-350', category: 'Protected Routes', title: 'Verify Unauthenticated Access to /settings Redirects to /', target: 'window.location', expected: 'Redirects to landing page' },

  // ==========================================
  // MODULE I: ADVANCED REAL-TIME & SYSTEM RECOVERY (TC-351 to TC-360)
  // ==========================================
  { id: 'TC-351', category: 'Real-Time Channel', title: 'Verify Supabase Realtime WebSocket Connection Handshake', target: 'supabase.channel("public:messages")', expected: 'State CONNECTED' },
  { id: 'TC-352', category: 'Real-Time Channel', title: 'Verify Real-Time Match Notification Broadcast Listener', target: 'supabase.channel("public:matches")', expected: 'Fires INSERT payload listener' },
  { id: 'TC-353', category: 'AI Study Plan Export', title: 'Verify "Export Study Plan" Action Button Click', target: 'button:contains("Export Plan")', expected: 'Downloads study plan document' },
  { id: 'TC-354', category: 'AI Study Plan Export', title: 'Verify "Share Study Plan" Modal Action Button', target: 'button:contains("Share Plan")', expected: 'Opens sharing modal link' },
  { id: 'TC-355', category: 'Advanced Filter', title: 'Verify Search Filter by Minimum Rating (4+ Stars)', target: 'select.rating-filter', expected: 'Filters users with 4+ stars' },
  { id: 'TC-356', category: 'Advanced Filter', title: 'Verify Search Filter by Online-Only Swappers', target: 'input[type="checkbox"].online-only', expected: 'Shows online users only' },
  { id: 'TC-357', category: 'Notification System', title: 'Verify Browser Push Notification Permission Prompt', target: 'Notification.requestPermission()', expected: 'Returns GRANTED' },
  { id: 'TC-358', category: 'Notification System', title: 'Verify Sound Effects Alert Toggle Switch', target: 'input.sound-alert-toggle', expected: 'Toggles audio alert state' },
  { id: 'TC-359', category: 'Mobile Safe Area', title: 'Verify Mobile Onboarding Submit Bar Elevation (pb-safe)', target: 'div.fixed.bottom-0.pb-safe', expected: 'Elevated above navigation bar' },
  { id: 'TC-360', category: 'Mobile Safe Area', title: 'Verify Mobile Navigation Bar High-Contrast Route Highlight', target: 'div.fixed.bottom-0 .active-nav-item', expected: 'High contrast primary styling' }
];

module.exports = {
  BASE_URL,
  testCases
};
